sudo: required
language: generic

notifications:
  email: false

env:
  - DEPLOY_STATUS_URL="$GH_BASE_URL/repos/$TRAVIS_REPO_SLUG/deployments/$TRAVIS_TAG/statuses"
script:
  - echo "fakie" #Just do a task here

before_deploy:
  - bash bin/setup.sh               #Install cf and aws
  - bash bin/ansibleSetup.sh        #Install ansible
  - bash bin/gatherSupplies.sh      #Get the files to deploy

deploy:
    - provider: script
      skip_cleanup: true
      script: bin/deploy.sh         #run ansible playbook to deploy app to bluemix
      on:
         all_branches: true
