# Publish this application to bluemix using ansible
---
- name: Publish the duo to Bluemix using Ansible
  hosts: localhost
  connection: local
  vars:
    username: "{{ lookup('env','BM_USER') }}"
    password: "{{ lookup('env','BM_PASS') }}"
    org: "{{ lookup('env','BM_ORG') }}"
    space: "{{ lookup('env','BM_SPACE') }}"
  tasks:
    - name: CF Login
      shell: "cf login -a https://api.ng.bluemix.net -u {{ username }} -p {{ password  }} -o {{ org }} -s {{ space }}"
      no_log: True
    - name: PWD, ls SHELL
      shell: "pwd; ls"
      register: pwdls
    - debug: msg="{{ pwdls.stdout }}"
    - name: CF Push build1
      shell: "cf push -f manifest.yml -u none"
      args:
        chdir: build1
    - name: CF Push build2
      shell: "cf push -f manifest.yml -u none"
      args:
        chdir: build1